In [35]:
import scipy.io
from pathlib import Path
import numpy as np
data = scipy.io.loadmat(Path('../data/ar/varForBumps135_100.mat'))

In [4]:
data.keys()

dict_keys(['__header__', '__version__', '__globals__', 'coeff10', 'conds', 'condsB', 'data', 'info', 'latent10', 'normedscore10', 'score10', 'subjects', 'subjectsF', 'x', 'x20', 'x5', 'y', 'y20', 'y5'])

In [10]:
data['info']
# Sampling freq: 100Hz
# Bandwidth filter 1-35 Hz
# Trial length onset, sep
# Conditions: TargetFan1, TargetFan2, FoilFan1, FoilFan2

array(['varibles for HSMM code from Qiong; 100 Hz sampling freq.; filter 1 to 35 Hz;lenght trials[Onset, sep], conditions: TargetFan1, TagetFan2, FoilFan1, FoilFan2'],
      dtype='<U156')

In [22]:
# Begin of epoch?
print(data['x'].shape)
data['x']

(14496, 1)


array([[      1],
       [    137],
       [    241],
       ...,
       [1692028],
       [1692166],
       [1692307]])

In [32]:
# End of epoch
print(data['y'].shape)
data['y']

(14496, 1)


array([[    136],
       [    240],
       [    359],
       ...,
       [1692165],
       [1692306],
       [1692481]])

In [45]:
for start, end in zip(data['x'], data['y']):
    # All epoch timings
    # NOTE: NOT ZERO-INDEXED, INDEX 1 IS FIRST SAMPLE
    print(start, end)

[1] [136]
[137] [240]
[241] [359]
[360] [453]
[454] [592]
[593] [709]
[710] [800]
[801] [932]
[933] [1058]
[1059] [1248]
[1249] [1371]
[1372] [1465]
[1466] [1564]
[1565] [1655]
[1656] [1811]
[1812] [1934]
[1935] [2065]
[2066] [2178]
[2179] [2268]
[2269] [2382]
[2383] [2496]
[2497] [2638]
[2639] [2723]
[2724] [2820]
[2821] [2980]
[2981] [3068]
[3069] [3172]
[3173] [3309]
[3310] [3425]
[3426] [3527]
[3528] [3643]
[3644] [3753]
[3754] [3866]
[3867] [3948]
[3949] [4051]
[4052] [4195]
[4196] [4279]
[4280] [4406]
[4407] [4566]
[4567] [4683]
[4684] [4776]
[4777] [4866]
[4867] [4986]
[4987] [5073]
[5074] [5149]
[5150] [5342]
[5343] [5443]
[5444] [5530]
[5531] [5620]
[5621] [5719]
[5720] [5849]
[5850] [5940]
[5941] [6021]
[6022] [6124]
[6125] [6238]
[6239] [6343]
[6344] [6487]
[6488] [6567]
[6568] [6642]
[6643] [6742]
[6743] [6817]
[6818] [6951]
[6952] [7088]
[7089] [7198]
[7199] [7289]
[7290] [7362]
[7363] [7432]
[7433] [7574]
[7575] [7673]
[7674] [7777]
[7778] [7879]
[7880] [7946]
[7947] [808

In [44]:
# Every point of data, electrodes?
data['data'][0:137]

array([[10.993831 ,  8.723188 , 10.027045 , ...,  5.5633454,  4.691024 ,
        10.233817 ],
       [13.505087 , 11.234549 , 10.693406 , ...,  9.04013  ,  9.229184 ,
        13.818634 ],
       [13.468838 ,  9.2393055,  9.529629 , ...,  9.169965 ,  9.655204 ,
        14.178063 ],
       ...,
       [ 3.4505954,  3.7852283,  3.0477   , ...,  2.1767552, -1.1543489,
        -2.7878852],
       [ 5.2995434,  6.2415214,  5.163968 , ...,  3.698343 ,  4.100088 ,
         3.7230742],
       [-6.627756 , -6.254589 , -4.2560973, ..., 11.651623 , 13.535622 ,
        17.530716 ]], dtype=float32)

In [43]:
# For every sample, which participant does it belong to
print(data['subjects'].shape)
data['subjects']

(14496, 1)
